packages = ["pandas", "beautifulsoup4", "requests", "jinja2","plotly", "matplotlib", "numpy"]

plugins = ["https://pyscript.net/latest/plugins/python/py_tutor.py"]

[splashscreen]
    
enabled = false

